Enable support for multiple interfaces
WiMoVE-OSS/wimoved pull request #33
Opened 2023-03-22 12:38 UTC by dasGoogle

Closes #32

2023-03-22 12:40 UTC, dasGoogle commented
@Sohn123 @linaScience @rgwohlbold When testing, please from now on make sure to enable the hostapd global control interface, i.e. using
```bash
sudo hostapd ./hapd.conf -g /var/run/hostapd/global
```

2023-03-22 13:27 UTC, rgwohlbold requested changes
Seems to work on my machine. I left a few nit-picky comments around the code for you to review

2023-03-22 13:27 UTC, rgwohlbold commented on src/Station.cpp
> +Station::Station(std::string sockname, std::string mac) : vlan_id(std::nullopt) {
We should use member initialization (`: sockname(sockname), mac(mac)`) here. `this->sockname = sockname` is not very idiomatic in C++

2023-03-22 13:27 UTC, rgwohlbold commented on src/ipc/Caller.cpp
> +    std::this_thread::sleep_for(std::chrono::milliseconds(100));
We should remove the `sleep()` here

2023-03-22 15:50 UTC, dasGoogle commented
I have deployed the current version of this PR on our APs at the office. Appears to work quite well but we should probably test roaming some more tomorrow when we have more devices available.

2023-03-23 08:43 UTC, rgwohlbold approved these changes
Looks good now! :shipit:

2023-03-23 08:44 UTC, merged