[Draft] Unify logging
WiMoVE-OSS/wimoved pull request #60
Opened 2023-04-26 07:56 UTC by linaScience

2023-07-14 08:05 UTC, Sohn123 requested changes
I think the format you developed is good :) Just some minor corrections and nitpicks. So let's fix it and :shipit:

2023-07-14 08:05 UTC, Sohn123 commented on src/EventLoop.cpp
> +    WMLOG(INFO) << "Disconnected station: " << event->station.mac.string();
This sounds like we disconnected the station but rather the station decided to disconnect.

2023-07-14 08:05 UTC, Sohn123 commented on src/ipc/Socket.cpp
> +        throw std::runtime_error("Could not bind to socket " + dest_path + ": " + std::strerror(errno));
Colon missing.

2023-07-14 08:05 UTC, Sohn123 commented on src/ipc/Socket.cpp
> +        throw std::runtime_error(std::string("Could not send_command() to socket: ") + std::strerror(errno));
I would write `Could not send to socket: `

2023-07-14 08:05 UTC, Sohn123 commented on src/nl/Socket.cpp
> +    WMLOG(INFO) << "Deleted interface." << name;
Colon instead of dot

2023-07-14 11:40 UTC, Sohn123 commented
Please also rebase onto latest main so the pipeline is green.

2023-07-14 12:00 UTC, linaScience commented on src/Configuration.cpp
> +        WMLOG(DEBUG) << "Could not configure sockets. Using all " << socknames.size() << " sockets available.";
Does `"Found" << socknames.size() << "available sockets".` sound better?

2023-07-14 12:02 UTC, rgwohlbold commented on src/BridgePerVxlanRenderer.cpp
> +        throw std::runtime_error("Station with MAC: " + station.mac.string() + " has no vlan_id.");
In my opinion, we should use key-value pairs to give additional information, and move them to the end.
For this log message, I propose "Station has no vlan_id mac=<mac>", similar for the others

2023-07-14 13:46 UTC, rgwohlbold requested changes
Our goal here is to make our logs searchable.
For example, if I wanted to find all events relating to a  MAC address `00:00:00:00:00:01`, I would search for `station=00:00:00:00:00:01`.
For that reason, I propose the following changes:

- We should use unified keys, for example `station` instead of `station` or `mac`
- No whitespace between the `=` and the value
- We should put the key-value pairs last and leave out prepositions like `with` before the pairs.

2023-07-14 13:46 UTC, rgwohlbold commented on src/nl/Socket.cpp
> +    WMLOG(INFO) << "Deleted interface:" << name;
use `iface=`

2023-07-14 13:46 UTC, rgwohlbold commented on src/nl/Socket.cpp
> +    WMLOG(INFO) << "Connected interface=" << interface_name << " to bridge= " << bridge_name;
We should put the KV-pairs last

2023-07-17 10:41 UTC, linaScience commented on src/nl/Socket.cpp
> +    WMLOG(INFO) << "Connected interface=" << interface_name << " to bridge= " << bridge_name;
Would `"Connected iface=" << interface_name << " bridge=" << bridge_name;` fit here?
Or do you suggest something else for this case?

2023-07-18 07:58 UTC, Sohn123 approved these changes
For me it is fine now. Thanks for all the work you put in @linaScience What do you think @rgwohlbold ?

2023-07-18 11:37 UTC, rgwohlbold approved these changes
LGTM :shipit:

2023-07-18 12:29 UTC, merged