Update README.md
WiMoVE-OSS/wimoved pull request #66
Opened 2023-07-17 12:02 UTC by rgwohlbold

2023-07-17 13:03 UTC, dasGoogle requested changes

2023-07-17 13:03 UTC, dasGoogle commented on README.md
> +| `sockets`          |                    | Explicit list of hostapd sockets, comma-separated. Can be used for sockets not in `hapd_sockdir`                                                         |
This needs to be changed: sockets can be used instead of hapd_sockdir to manually configure the sockets. When set, hapd_sockdir will not be scanned for ports. These names are relative to the sockdir, i.e., you just want to use the filename of the socket here

2023-07-18 08:14 UTC, Sohn123 requested changes
When reviewing the README I noticed two things:
1. We should verify that the whitespace for the hostapd vlan file is correct and make people aware that whitespace is important. I think it has to be tab separated. That could be the issue rubens encountered.
2. Maybe we should update the local build instructions and tell people to create a build directory first and then run cmake in there. I personally really like it when I can just delete the build directory afterward. And we can just add it to the `.gitignore`

2023-07-18 08:14 UTC, Sohn123 commented on README.md
> +<img src="https://github.com/WiMoVE-OSS/wimoved/assets/25486288/802775f0-67a3-4396-9bab-b965f9c43f2e" width=600>
Nice that you included the image but in dark mode it is broken. Adding a white background would help.

2023-07-18 08:14 UTC, Sohn123 commented on README.md
> +| `cleanup_interval` | 10                 | Duration of the cleanup timer. Wimoved removes interfaces whenever the cleanup timer expires.                                                            |
Add the information that it is in seconds

2023-07-18 08:14 UTC, Sohn123 commented on README.md
> +```
Tell the people where they can find the built package afterward.

2023-07-21 07:29 UTC, rgwohlbold commented
> When reviewing the README I noticed two things:
> 
> 1. We should verify that the whitespace for the hostapd vlan file is correct and make people aware that whitespace is important. I think it has to be tab separated. That could be the issue rubens encountered.
> 2. Maybe we should update the local build instructions and tell people to create a build directory first and then run cmake in there. I personally really like it when I can just delete the build directory afterward. And we can just add it to the `.gitignore`

I checked the hostapd source code and verified that spaces or tabs are fine in `hostapd.vlan`.
The build directory seems to be mostly personal preference. Since the build works right now, I would leave it as-is.

2023-07-21 07:39 UTC, Sohn123 reviewed
Just one more suggestion :)

2023-07-21 07:39 UTC, Sohn123 commented on README.md
> +![](https://github.com/WiMoVE-OSS/wimoved/assets/25486288/6fc99e28-4ae8-41da-b0eb-0df441451a7b)
```suggestion
<p align="center">
 <img width="600px" src="https://github.com/WiMoVE-OSS/wimoved/assets/25486288/6fc99e28-4ae8-41da-b0eb-0df441451a7b"/>
</p>
```

This will align the image in the center. I think this looks a bit nicer:
![image](https://github.com/WiMoVE-OSS/wimoved/assets/39831045/5e9d458d-b205-43ea-a42e-1dc4fe0cab66)

![image](https://github.com/WiMoVE-OSS/wimoved/assets/39831045/fa249fa9-81ca-4c3c-a220-f68f1da027ba)

2023-07-23 08:52 UTC, dasGoogle commented
One more thing: We wanted to add a reference to the existing issue in FRR, didn't we?

2023-07-24 09:56 UTC, dasGoogle approved these changes

2023-07-24 09:57 UTC, Sohn123 approved these changes
Nice, thanks for all the work you put in :shipit: 🚀 🥳

2023-07-24 09:57 UTC, merged